// <auto-generated />
namespace WebApplication_LibraryManagementProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class secondMigrations3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(secondMigrations3));
        
        string IMigrationMetadata.Id
        {
            get { return "202306211810570_secondMigrations3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
